# Generated by Django 2.2 on 2019-12-02 21:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('objests', django.db.models.manager.Manager()),
            ],
        ),
    ]
