# Generated by Django 2.2 on 2020-01-03 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20200103_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 14, 40, 2, 658128)),
            preserve_default=False,
        ),
    ]
